import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { admin, bearer, phoneNumber } from 'better-auth/plugins';
import { expo } from '@better-auth/expo';
import { db } from '../db/client';
import { env } from '../env';
import * as authSchema from '../db/auth-schema';
import { sendEmail } from './email';
import { localeFromAuthUrl, resetPasswordEmail, verificationEmail } from './email-templates';
import { createAuthSecondaryStorage } from './secondary-storage';
import { sendSms } from './sms';
import { createRedisConnection } from '../queue/redis';

/**
 * BetterAuth instance — the single source of truth for authentication.
 *
 * Security note: password hashing, token signing, session storage and CSRF
 * protection are all handled by BetterAuth. We do NOT roll our own crypto here.
 */
export const auth = betterAuth({
  // Sign cookies/tokens/sessions. Validated (>= 32 chars) in env.ts.
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,

  // Existing Drizzle + PostgreSQL setup. `authSchema` is generated by the
  // BetterAuth CLI (`pnpm auth:generate`).
  database: drizzleAdapter(db, {
    provider: 'pg',
    schema: authSchema,
  }),

  // --- Email + password (BetterAuth core) ---
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Unverified sign-in resends the mail when `sendOnSignIn` is on. The web
    // client passes a locale `callbackURL` so the link returns to the site,
    // not the API origin (`/`).
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      console.log(`[auth] sending password-reset email to ${user.email}`);
      const mail = resetPasswordEmail({ url, locale: localeFromAuthUrl(url) });
      await sendEmail({ to: user.email, ...mail });
    },
    // Reset is unauthenticated — drop every session, then they sign in again.
    revokeSessionsOnPasswordReset: true,
    onPasswordReset: async ({ user }) => {
      console.log(`[auth] password reset completed for ${user.email}`);
    },
  },
  emailVerification: {
    sendOnSignUp: true,
    sendOnSignIn: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url }) => {
      console.log(`[auth] sending verification email to ${user.email}`);
      const mail = verificationEmail({
        email: user.email,
        url,
        locale: localeFromAuthUrl(url),
      });
      await sendEmail({ to: user.email, ...mail });
    },
  },

  // --- Social login: Google (web redirect flow) ---
  // Enabled only when both env vars are set. The redirect callback that must be
  // registered in Google Cloud Console is `${BETTER_AUTH_URL}/api/auth/callback/google`.
  // `accessType: 'offline'` requests a refresh token (stored in the account table).
  socialProviders: {
    ...(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET
      ? {
          google: {
            clientId: env.GOOGLE_CLIENT_ID,
            clientSecret: env.GOOGLE_CLIENT_SECRET,
            prompt: 'select_account',
            accessType: 'offline',
          },
        }
      : {}),
  },

  // Link a Google login to an existing user with the same email. Safe to trust
  // Google here because Google asserts verified emails; do NOT add providers
  // that don't verify emails (account-takeover risk).
  account: {
    accountLinking: {
      enabled: true,
      trustedProviders: ['google'],
    },
  },

  // --- Session expiry + rotation (the "access + refresh" requirement) ---
  // The session is the credential. `updateAge` slides the expiry forward each
  // day the session is used, so active users never get logged out, while idle
  // sessions still expire after `expiresIn`. This is BetterAuth's native
  // rotation — no custom JWT/refresh code.
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60 * 24, // rotate/extend once per day of use
    freshAge: 60 * 60 * 24, // "fresh" window for sensitive operations
  },

  // --- Security ---
  // `carpool://` is the mobile app's scheme (apps/mobile/app.json) — needed in
  // every environment, since the shipped production app uses it too.
  // `exp://**` only covers Expo Go / dev-client sessions over a LAN IP during
  // development, so it's gated out of production rather than widening the
  // CSRF-relevant trusted-origins allowlist unconditionally. Both are
  // compile-time app constants, not per-deployment config, so they're
  // hardcoded here rather than added to TRUSTED_ORIGINS in env.ts.
  trustedOrigins: [
    ...env.TRUSTED_ORIGINS,
    'carpool://',
    ...(process.env.NODE_ENV === 'production' ? [] : ['exp://**']),
  ],
  advanced: {
    // CSRF is enforced via origin checking against trustedOrigins (on by
    // default — we do NOT disable it). Cookies are httpOnly + sameSite=lax.
    // Secure cookies are keyed to the deployment URL scheme, NOT NODE_ENV: a
    // production-built image (NODE_ENV=production) is routinely run locally over
    // http://localhost in Docker, where `Secure` cookies would be dropped by the
    // browser and break sessions. https:// → Secure on; http:// → Secure off.
    useSecureCookies: env.BETTER_AUTH_URL.startsWith('https://'),
    defaultCookieAttributes: {
      httpOnly: true,
      sameSite: 'lax',
    },
  },

  // --- Rate limiting (Redis via secondaryStorage) ---
  // Shared across API replicas and survives restarts. Custom rules stay tight
  // on the auth endpoints that are worth brute-forcing.
  rateLimit: {
    enabled: true,
    storage: 'secondary-storage',
    window: 60,
    max: 100,
    customRules: {
      '/sign-in/email': { window: 10, max: 5 },
      '/sign-up/email': { window: 60, max: 5 },
      '/request-password-reset': { window: 60, max: 3 },
      '/send-verification-email': { window: 60, max: 3 },
      '/phone-number/send-otp': { window: 60, max: 3 },
    },
  },

  user: {
    // Immediate wipe is off. Settings schedules a 30-day hold on
    // POST /account/deletion; the daily worker purges after that.
    deleteUser: {
      enabled: false,
    },
  },

  secondaryStorage: createAuthSecondaryStorage(createRedisConnection('auth')),

  plugins: [
    // Roles: `user` (default) and `admin`. Two roles only — no permissions engine.
    admin({
      defaultRole: 'user',
      adminRoles: ['admin'],
    }),
    // Phone number + OTP. The OTP is delivered via the console SMS stub in dev.
    phoneNumber({
      otpLength: 6,
      expiresIn: 300, // 5 minutes
      sendOTP: async ({ phoneNumber: to, code }) => {
        await sendSms({ to, text: `Your Carpool verification code is ${code}` });
      },
      // Verifying an OTP for an unknown number creates an account.
      signUpOnVerification: {
        getTempEmail: (phone) => `${phone.replace(/[^0-9]/g, '')}@phone.carpool.local`,
        getTempName: (phone) => phone,
      },
    }),
    // Bearer tokens for mobile/API clients: read the `set-auth-token` response
    // header on sign-in, send it back as `Authorization: Bearer <token>`.
    bearer(),
    // React Native (Expo) support: registers the `carpool://` deep-link
    // callback for OAuth and lets `expoClient` (mobile's auth-client plugin)
    // persist the session via a custom `expo-origin` request header instead
    // of a browser cookie jar.
    expo(),
  ],
});

export type Auth = typeof auth;

/** Inferred session + user types (no `any`). Includes plugin fields (e.g. role). */
export type AuthSession = typeof auth.$Infer.Session.session;
export type AuthUser = typeof auth.$Infer.Session.user;
