import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { admin, bearer, phoneNumber } from 'better-auth/plugins';
import { db } from '../db/client';
import { env } from '../env';
import * as authSchema from '../db/auth-schema';
import { sendEmail } from './email';
import { sendSms } from './sms';

/**
 * BetterAuth instance — the single source of truth for authentication.
 *
 * Security note: password hashing, token signing, session storage and CSRF
 * protection are all handled by BetterAuth. We do NOT roll our own crypto here.
 */
export const auth = betterAuth({
  // Sign cookies/tokens/sessions. Validated (>= 32 chars) in env.ts.
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,

  // Existing Drizzle + PostgreSQL setup. `authSchema` is generated by the
  // BetterAuth CLI (`pnpm auth:generate`).
  database: drizzleAdapter(db, {
    provider: 'pg',
    schema: authSchema,
  }),

  // --- Email + password (BetterAuth core) ---
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Unverified users cannot sign in until they click the verification link.
    // In dev (console stub) the link is printed to the API logs; with SMTP_HOST
    // set it is emailed for real.
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: 'Reset your Carpool password',
        text: `Reset your password with this link: ${url}`,
      });
    },
    onPasswordReset: async ({ user }) => {
      console.log(`[auth] password reset completed for ${user.email}`);
    },
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: 'Verify your Carpool email',
        text: `Verify your email with this link: ${url}`,
      });
    },
  },

  // --- Session expiry + rotation (the "access + refresh" requirement) ---
  // The session is the credential. `updateAge` slides the expiry forward each
  // day the session is used, so active users never get logged out, while idle
  // sessions still expire after `expiresIn`. This is BetterAuth's native
  // rotation — no custom JWT/refresh code.
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60 * 24, // rotate/extend once per day of use
    freshAge: 60 * 60 * 24, // "fresh" window for sensitive operations
  },

  // --- Security ---
  trustedOrigins: env.TRUSTED_ORIGINS,
  advanced: {
    // CSRF is enforced via origin checking against trustedOrigins (on by
    // default — we do NOT disable it). Cookies are httpOnly + sameSite=lax and
    // become Secure automatically in production.
    useSecureCookies: process.env.NODE_ENV === 'production',
    defaultCookieAttributes: {
      httpOnly: true,
      sameSite: 'lax',
    },
  },

  // --- Rate limiting (BetterAuth built-in) ---
  // In-memory for dev. TODO(prod): configure `secondaryStorage` (Redis) and set
  // `storage: 'secondary-storage'` so limits + sessions survive restarts and
  // scale across instances. See the commented `secondaryStorage` slot below.
  rateLimit: {
    enabled: true,
    window: 60,
    max: 100,
    customRules: {
      '/sign-in/email': { window: 10, max: 5 },
      '/sign-up/email': { window: 60, max: 5 },
      '/phone-number/send-otp': { window: 60, max: 3 },
    },
  },

  // TODO(prod): back rate limiting + sessions with Redis.
  // secondaryStorage: {
  //   get: (key) => redis.get(key),
  //   set: (key, value, ttl) => redis.set(key, value, 'EX', ttl ?? 60),
  //   delete: (key) => redis.del(key),
  // },

  plugins: [
    // Roles: `user` (default) and `admin`. Two roles only — no permissions engine.
    admin({
      defaultRole: 'user',
      adminRoles: ['admin'],
    }),
    // Phone number + OTP. The OTP is delivered via the console SMS stub in dev.
    phoneNumber({
      otpLength: 6,
      expiresIn: 300, // 5 minutes
      sendOTP: async ({ phoneNumber: to, code }) => {
        await sendSms({ to, text: `Your Carpool verification code is ${code}` });
      },
      // Verifying an OTP for an unknown number creates an account.
      signUpOnVerification: {
        getTempEmail: (phone) => `${phone.replace(/[^0-9]/g, '')}@phone.carpool.local`,
        getTempName: (phone) => phone,
      },
    }),
    // Bearer tokens for mobile/API clients: read the `set-auth-token` response
    // header on sign-in, send it back as `Authorization: Bearer <token>`.
    bearer(),
  ],
});

export type Auth = typeof auth;

/** Inferred session + user types (no `any`). Includes plugin fields (e.g. role). */
export type AuthSession = typeof auth.$Infer.Session.session;
export type AuthUser = typeof auth.$Infer.Session.user;
