import { relations } from 'drizzle-orm';
import { pgTable, text, date, timestamp } from 'drizzle-orm/pg-core';
import { user } from './auth-schema';

/**
 * `driver_eligibility` — what a driver declares about themselves, as opposed to
 * what they upload.
 *
 * Today that is one column: the date of birth behind the "at least 18 years
 * old" rule. It lives in its own table rather than on `user` because
 * auth-schema.ts is generated by the BetterAuth CLI and must not be hand-edited;
 * a separate table keeps this domain field out of the way of the next
 * regeneration. It is also the natural home for whatever the eligibility rules
 * grow next (a licence province, an issue date) without touching auth at all.
 *
 * One row per driver — `userId` is the primary key, so a declaration is upserted
 * rather than accumulated. Unlike a document, there is no history worth keeping:
 * a birth date is a fact, not a submission.
 *
 * After editing the columns, regenerate + apply the migration:
 * `pnpm --filter @carpool/api db:generate` then `db:migrate`.
 */
export const driverEligibility = pgTable('driver_eligibility', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  /**
   * `date`, not `timestamp`: a birth date has no time and no zone, and storing
   * it as an instant is how someone born on the 1st becomes a day younger west
   * of UTC. Drizzle gives it back as a plain `YYYY-MM-DD`.
   */
  dateOfBirth: date('date_of_birth').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const driverEligibilityRelations = relations(driverEligibility, ({ one }) => ({
  driver: one(user, {
    fields: [driverEligibility.userId],
    references: [user.id],
  }),
}));
