import { relations } from 'drizzle-orm';
import { pgTable, text, date, boolean, timestamp } from 'drizzle-orm/pg-core';
import { user } from './auth-schema';

/**
 * `driver_eligibility` — what a driver declares about themselves, as opposed to
 * what they upload.
 *
 * Columns are each declared independently (its own PUT route, its own
 * mutation) so a row can exist with any subset of them set:
 *
 *   dateOfBirth           — the "at least 18 years old" rule (`PUT /eligibility`)
 *   licenseNumber         — the number printed on the permis, as opposed to the
 *                           scanned `driver_document` row proving it — that
 *                           upload stays optional, the number is what's
 *                           mandatory (`PUT /eligibility/license-number`)
 *   firstName / lastName  — the driver's LEGAL name as printed on the permis,
 *                           which an admin cross-checks against `licenseNumber`
 *                           — may differ from the account's display name
 *                           (`PUT /eligibility/name`)
 *   hasValidLicense /
 *   meetsRequirements     — the ride-creation "Conditions d'éligibilité" step,
 *                           reduced to two yes/no self-declarations, the same
 *                           way `vehicle.hasInsurance` satisfies insurance.
 *                           Saved together (`PUT /eligibility/confirmation`)
 *                           since the UI always shows and answers them as a
 *                           pair.
 *
 * It lives in its own table rather than on `user` because auth-schema.ts is
 * generated by the BetterAuth CLI and must not be hand-edited; a separate
 * table keeps these domain fields out of the way of the next regeneration. It
 * is also the natural home for whatever the eligibility rules grow next (a
 * licence province, an issue date) without touching auth at all.
 *
 * One row per driver — `userId` is the primary key, so a declaration is upserted
 * rather than accumulated. Unlike a document, there is no history worth keeping:
 * a birth date, a name or a licence number is a fact, not a submission.
 *
 * After editing the columns, regenerate + apply the migration:
 * `pnpm --filter @carpool/api db:generate` then `db:migrate`.
 */
export const driverEligibility = pgTable('driver_eligibility', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  /**
   * `date`, not `timestamp`: a birth date has no time and no zone, and storing
   * it as an instant is how someone born on the 1st becomes a day younger west
   * of UTC. Drizzle gives it back as a plain `YYYY-MM-DD`.
   */
  dateOfBirth: date('date_of_birth'),
  /** The number printed on the driver's licence. */
  licenseNumber: text('license_number'),
  /** Legal first/last name as printed on the licence — see table doc comment. */
  firstName: text('first_name'),
  lastName: text('last_name'),
  /** Self-declared "yes/no" answers behind the ride-creation eligibility step — see table doc comment. */
  hasValidLicense: boolean('has_valid_license'),
  meetsRequirements: boolean('meets_requirements'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const driverEligibilityRelations = relations(driverEligibility, ({ one }) => ({
  driver: one(user, {
    fields: [driverEligibility.userId],
    references: [user.id],
  }),
}));
