// Drizzle schema entry point.
//
// The authentication tables (user, session, account, verification + plugin
// fields) are generated by the BetterAuth CLI into ./auth-schema.ts. Do not
// hand-edit them — regenerate with `pnpm --filter @carpool/api auth:generate`.
export * from './auth-schema';

// Domain table exports are appended below by `pnpm gen backend-feature`.
export * from './trajet-schema';
export * from './review';
// plop:tables
export * from './message';
