// Drizzle schema entry point.
//
// The authentication tables (user, session, account, verification + plugin
// fields) are generated by the BetterAuth CLI into ./auth-schema.ts. Do not
// hand-edit them — regenerate with `pnpm --filter @carpool/api auth:generate`.
export * from './auth-schema';

// Domain tables. New ones are appended below by `pnpm gen backend-feature` —
// the marker is what the generator anchors to, so keep it.
// plop:tables
export * from './document';
export * from './eligibility';
export * from './trajet-schema';
export * from './review';
export * from './message';
export * from './notification';
