// Drizzle schema entry point.
//
// The authentication tables (user, session, account, verification + plugin
// fields) are generated by the BetterAuth CLI into ./auth-schema.ts. Do not
// hand-edit them — regenerate with `pnpm --filter @carpool/api auth:generate`.
export * from './auth-schema';

// TODO: domain tables (rides, bookings, …) go here as the product grows.
export * from './trajet-schema';
